version: 2
jobs:
  build:
    machine:
      image: ubuntu-2204:2022.04.2
    steps:
      - checkout
     # start proprietary DB using private Docker image
     # with credentials stored in the UI
      - run: |
         echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin

     # build the application image
      - run:
          # Builds a docker image to push to Docker Hub
          # Tag (-t) pattern is below, where CircleCI
          # to get the Dockerfile from the current directory.
          # <docker_hub_username/docker-hub-password:version>.
          name: Build Docker image
          command: docker build -t $DOCKERHUB_USER/gate_io_collector:1.0 .
      - deploy:
          name: Push application Docker image
          command: |
            if [ "$ {CIRCLE_BRANCH}" == "master" ]; then
              docker push "${DOCKERHUB_USER}/gate_io_collector:1.0"
            fi