version: 2
jobs:
  build:
    docker:
      - image: cimg/go:1.17
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      # ... steps for building/testing app ...

      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - run:
          name: Build Docker image
          command: |
            TAG=1.0.$CIRCLE_BUILD_NUM
            docker build -t $DOCKERHUB_USER/gate_io_collector:$TAG .
      - deploy:
          name: Push application Docker image
          command: |
            TAG=1.0.$CIRCLE_BUILD_NUM
            docker push $DOCKERHUB_USER/gate_io_collector:$TAG
